apiVersion: v1
appVersion: v1.56.0
description: A Helm chart for rclone
name: kube-rclone
version: 0.1.1
keywords:
    - rclone
home: https://rclone.org/
icon: https://rclone.org/img/rclone-16x16.png
sources:
    - https://github.com/korni22d/kube-rclone
    - https://hub.docker.com/r/rclone/rclone
maintainers:
    - name: korni22
