# Default values for kube-rclone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
images:
  initContainer:
    repository: busybox
    tag: latest
  container:
    repository: docker.io/rclone/rclone
    tag: 1.56.0
    namespace: rclone
  pullPolicy: IfNotPresent

# imagePullSecrets:

rclone:
  #  remote to mount from rclone config
  remote: "gc_crypt:"
  # mount path for  remote
  path: /mnt/gd_crypt
  # read only file system for remote (to protect from deletion of files)
  readOnly: false
  # additional arguments for customising rclone
  # mount options can be found here - https://rclone.org/commands/rclone_mount/#options
  additionalArgs:
    - --fast-list
    - --log-level=INFO
    - --buffer-size=10M
    - --vfs-cache-mode=full
    - --drive-acknowledge-abuse=true
    - --vfs-read-ahead=10M
    - --vfs-read-chunk-size=10M
    - --vfs-cache-max-size=100G
    - --uid=1000
    - --gid=1000
    - --allow-other

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # requests:
  #   cpu: 250m
  #   memory: 1Gi
  # limits:
  #   cpu: 350m
  #   memory: 2Gi

nodeSelector: {}
